application: livingorgans
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /datastore_admin
  script: google.appengine.ext.datastore_admin.main.APP
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: setuptools
  version: "0.6c11"
- name: webapp2
  version: "2.3"

builtins:
- deferred: on
